"""N-Gram language model (Unigram / Bigram / Trigram) with Laplace smoothing.

Academic focus: this is a genuine implementation of n-gram language modeling used
for emotion classification. For each emotion class we build separate n-gram count
distributions over the training corpus, then score an input sequence by the (log)
likelihood that the words/syllables are generated by that class's model.

Smoothing: add-one (Laplace) smoothing to avoid zero probabilities for unseen n-grams.

The model supports:
  - P(word)                              (Unigram)
  - P(word | previous_word)              (Bigram)
  - P(word | previous_two_words)         (Trigram)

N-gram scores are combined into an emotion score in the EmotionModel.
"""

from __future__ import annotations

import math
from collections import defaultdict


def make_ngrams(tokens: list[str], n: int) -> list[tuple[str, ...]]:
    """Generate n-grams from a token list with start padding."""
    if n == 1:
        return [(t,) for t in tokens]
    padded = ["<s>"] * (n - 1) + tokens
    return [tuple(padded[i : i + n]) for i in range(len(padded) - n + 1)]


class NGramModel:
    """A single emotion-class n-gram model over a token vocabulary."""

    def __init__(self, n: int = 3):
        self.n = n
        self.counts: dict[tuple[str, ...], int] = defaultdict(int)
        self.context_counts: dict[tuple[str, ...], int] = defaultdict(int)
        self.vocabulary: set[str] = set()
        self.total_ngrams = 0

    def fit(self, documents: list[list[str]]) -> None:
        """Fit on a list of tokenized documents."""
        for doc in documents:
            for ngram in make_ngrams(doc, self.n):
                self.counts[ngram] += 1
                self.total_ngrams += 1
                self.vocabulary.update(ngram)
            if self.n > 1:
                for context in self._contexts(doc):
                    self.context_counts[context] += 1

    def _contexts(self, doc: list[str]) -> list[tuple[str, ...]]:
        if self.n == 1:
            return []
        nlist = make_ngrams(doc, self.n)
        return [n[:-1] for n in nlist]

    @property
    def vocab_size(self) -> int:
        return len(self.vocabulary)

    def unigram_prob(self, word: str) -> float:
        """P(word) with Laplace smoothing."""
        return (self.counts.get((word,), 0) + 1) / (self.total_ngrams + self.vocab_size)

    def bigram_prob(self, prev: str, word: str) -> float:
        """P(word | prev) with Laplace smoothing."""
        count = self.counts.get((prev, word), 0)
        context = self.context_counts.get((prev,), 0)
        return (count + 1) / (context + self.vocab_size)

    def trigram_prob(self, prev2: str, prev: str, word: str) -> float:
        """P(word | prev2, prev) with Laplace smoothing."""
        count = self.counts.get((prev2, prev, word), 0)
        context = self.context_counts.get((prev2, prev), 0)
        return (count + 1) / (context + self.vocab_size)

    def score(self, tokens: list[str], use_interpolation: bool = True) -> float:
        """Log-likelihood of token sequence under this model.

        Combines unigram, bigram, and trigram probabilities by interpolation with
        weights that depend on n (more context = more weight but subject to data sparsity).
        """
        if not tokens:
            return 0.0

        if self.n == 1:
            return sum(math.log(self.unigram_prob(t)) for t in tokens)

        bigram_count = 0
        log_likelihood = 0.0
        # Iterate over a sliding window of up to n tokens.
        padded = ["<s>"] * (self.n - 1) + tokens
        for i in range(len(padded) - 1):
            word = padded[i + 1]
            prev = padded[i]
            if self.n >= 3 and i >= 1:
                prev2 = padded[i - 1]
            else:
                prev2 = None

            unigram_p = self.unigram_prob(word)
            bigram_p = self.bigram_prob(prev, word)

            # Interpolate. Weights: more smoothing weight to lower-order for sparse data.
            if prev2 is not None and self.n >= 3:
                trigram_p = self.trigram_prob(prev2, prev, word)
                p = 0.2 * unigram_p + 0.3 * bigram_p + 0.5 * trigram_p
            else:
                p = 0.4 * unigram_p + 0.6 * bigram_p

            log_likelihood += math.log(max(p, 1e-12))
            bigram_count += 1

        # Normalize by sequence length so longer messages don't dominate.
        if bigram_count:
            log_likelihood /= (bigram_count + 1)
        return log_likelihood

    def sequence_logprob(self, tokens: list[str]) -> float:
        return math.log(self.probability(tokens)) if tokens else 0.0

    def probability(self, tokens: list[str]) -> float:
        """Raw probability (product) of a token sequence under the model."""
        if not tokens:
            return 1.0
        padded = ["<s>"] * (self.n - 1) + tokens
        prob = 1.0
        for i in range(len(padded) - 1):
            word = padded[i + 1]
            prev = padded[i]
            if self.n >= 3 and i >= 1:
                prev2 = padded[i - 1]
                p = self.trigram_prob(prev2, prev, word)
            elif self.n >= 2:
                p = self.bigram_prob(prev, word)
            else:
                p = self.unigram_prob(word)
            prob *= max(p, 1e-12)
        return prob


class NGramEnsemble:
    """Unigram + Bigram + Trigram ensemble scoring across emotions.

    Holds one NGramModel per n-order per emotion class.
    """

    def __init__(self, emotions: list[str], n_orders: list[int] | None = None):
        self.emotions = emotions
        self.n_orders = n_orders or [1, 2, 3]
        # models[emotion][n] -> NGramModel
        self.models: dict[str, dict[int, NGramModel]] = {
            e: {n: NGramModel(n) for n in self.n_orders} for e in emotions
        }

    def fit(self, data: dict[str, list[list[str]]]) -> None:
        """Fit all models. data: {emotion: [list_of_token_lists]}."""
        for emotion, docs in data.items():
            if emotion not in self.models:
                continue
            for n in self.n_orders:
                self.models[emotion][n].fit(docs)

    def score(self, emotion: str, tokens: list[str]) -> float:
        """Aggregate log-likelihood across n-orders for an emotion class."""
        if emotion not in self.models:
            raise KeyError(f"Unknown emotion: {emotion}")
        total = 0.0
        for n, model in self.models[emotion].items():
            total += model.score(tokens)
        return total

    def scores(self, tokens: list[str]) -> dict[str, float]:
        """Raw (unnormalized) score per emotion class."""
        return {e: self.score(e, tokens) for e in self.emotions}
